export default {
  SET_TOKEN: 'SET_TOKEN',
  SET_USER: 'SET_USER',
  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
  ADD_VISITED_VIEWS: 'ADD_VISITED_VIEWS',
  DEL_VISITED_VIEWS: 'DEL_VISITED_VIEWS',
  SET_ROUTES: 'SET_ROUTES'
}
